// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.sunbird.akka.core;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageOption}
   */
  public enum MessageOption
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SEND_AND_FORGET = 0;</code>
     */
    SEND_AND_FORGET(0),
    /**
     * <code>GET_BACK_RESPONSE = 1;</code>
     */
    GET_BACK_RESPONSE(1),
    ;

    /**
     * <code>SEND_AND_FORGET = 0;</code>
     */
    public static final int SEND_AND_FORGET_VALUE = 0;
    /**
     * <code>GET_BACK_RESPONSE = 1;</code>
     */
    public static final int GET_BACK_RESPONSE_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageOption valueOf(int value) {
      return forNumber(value);
    }

    public static MessageOption forNumber(int value) {
      switch (value) {
        case 0: return SEND_AND_FORGET;
        case 1: return GET_BACK_RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageOption>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageOption> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageOption>() {
            public MessageOption findValueByNumber(int number) {
              return MessageOption.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.sunbird.akka.core.MessageProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageOption[] VALUES = values();

    public static MessageOption valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageOption(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageOption)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string targetActorName = 1;</code>
     */
    boolean hasTargetActorName();
    /**
     * <code>required string targetActorName = 1;</code>
     */
    java.lang.String getTargetActorName();
    /**
     * <code>required string targetActorName = 1;</code>
     */
    com.google.protobuf.ByteString
        getTargetActorNameBytes();

    /**
     * <code>optional string sourceActorName = 2;</code>
     */
    boolean hasSourceActorName();
    /**
     * <code>optional string sourceActorName = 2;</code>
     */
    java.lang.String getSourceActorName();
    /**
     * <code>optional string sourceActorName = 2;</code>
     */
    com.google.protobuf.ByteString
        getSourceActorNameBytes();

    /**
     * <code>optional string performOperation = 3;</code>
     */
    boolean hasPerformOperation();
    /**
     * <code>optional string performOperation = 3;</code>
     */
    java.lang.String getPerformOperation();
    /**
     * <code>optional string performOperation = 3;</code>
     */
    com.google.protobuf.ByteString
        getPerformOperationBytes();

    /**
     * <code>optional string id = 4;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 4;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 4;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional .MessageOption msgOption = 5;</code>
     */
    boolean hasMsgOption();
    /**
     * <code>optional .MessageOption msgOption = 5;</code>
     */
    org.sunbird.akka.core.MessageProtos.MessageOption getMsgOption();

    /**
     * <code>optional string payload = 6;</code>
     */
    boolean hasPayload();
    /**
     * <code>optional string payload = 6;</code>
     */
    java.lang.String getPayload();
    /**
     * <code>optional string payload = 6;</code>
     */
    com.google.protobuf.ByteString
        getPayloadBytes();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      targetActorName_ = "";
      sourceActorName_ = "";
      performOperation_ = "";
      id_ = "";
      msgOption_ = 0;
      payload_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              targetActorName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sourceActorName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              performOperation_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              id_ = bs;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              org.sunbird.akka.core.MessageProtos.MessageOption value = org.sunbird.akka.core.MessageProtos.MessageOption.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                msgOption_ = rawValue;
              }
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              payload_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sunbird.akka.core.MessageProtos.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sunbird.akka.core.MessageProtos.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sunbird.akka.core.MessageProtos.Message.class, org.sunbird.akka.core.MessageProtos.Message.Builder.class);
    }

    private int bitField0_;
    public static final int TARGETACTORNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object targetActorName_;
    /**
     * <code>required string targetActorName = 1;</code>
     */
    public boolean hasTargetActorName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string targetActorName = 1;</code>
     */
    public java.lang.String getTargetActorName() {
      java.lang.Object ref = targetActorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetActorName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string targetActorName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTargetActorNameBytes() {
      java.lang.Object ref = targetActorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetActorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCEACTORNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object sourceActorName_;
    /**
     * <code>optional string sourceActorName = 2;</code>
     */
    public boolean hasSourceActorName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sourceActorName = 2;</code>
     */
    public java.lang.String getSourceActorName() {
      java.lang.Object ref = sourceActorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceActorName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sourceActorName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSourceActorNameBytes() {
      java.lang.Object ref = sourceActorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceActorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERFORMOPERATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object performOperation_;
    /**
     * <code>optional string performOperation = 3;</code>
     */
    public boolean hasPerformOperation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string performOperation = 3;</code>
     */
    public java.lang.String getPerformOperation() {
      java.lang.Object ref = performOperation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          performOperation_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string performOperation = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPerformOperationBytes() {
      java.lang.Object ref = performOperation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        performOperation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 4;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string id = 4;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGOPTION_FIELD_NUMBER = 5;
    private int msgOption_;
    /**
     * <code>optional .MessageOption msgOption = 5;</code>
     */
    public boolean hasMsgOption() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .MessageOption msgOption = 5;</code>
     */
    public org.sunbird.akka.core.MessageProtos.MessageOption getMsgOption() {
      @SuppressWarnings("deprecation")
      org.sunbird.akka.core.MessageProtos.MessageOption result = org.sunbird.akka.core.MessageProtos.MessageOption.valueOf(msgOption_);
      return result == null ? org.sunbird.akka.core.MessageProtos.MessageOption.SEND_AND_FORGET : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 6;
    private volatile java.lang.Object payload_;
    /**
     * <code>optional string payload = 6;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string payload = 6;</code>
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          payload_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string payload = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTargetActorName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, targetActorName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceActorName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, performOperation_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, id_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, msgOption_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, targetActorName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceActorName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, performOperation_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, id_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, msgOption_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sunbird.akka.core.MessageProtos.Message)) {
        return super.equals(obj);
      }
      org.sunbird.akka.core.MessageProtos.Message other = (org.sunbird.akka.core.MessageProtos.Message) obj;

      boolean result = true;
      result = result && (hasTargetActorName() == other.hasTargetActorName());
      if (hasTargetActorName()) {
        result = result && getTargetActorName()
            .equals(other.getTargetActorName());
      }
      result = result && (hasSourceActorName() == other.hasSourceActorName());
      if (hasSourceActorName()) {
        result = result && getSourceActorName()
            .equals(other.getSourceActorName());
      }
      result = result && (hasPerformOperation() == other.hasPerformOperation());
      if (hasPerformOperation()) {
        result = result && getPerformOperation()
            .equals(other.getPerformOperation());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasMsgOption() == other.hasMsgOption());
      if (hasMsgOption()) {
        result = result && msgOption_ == other.msgOption_;
      }
      result = result && (hasPayload() == other.hasPayload());
      if (hasPayload()) {
        result = result && getPayload()
            .equals(other.getPayload());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTargetActorName()) {
        hash = (37 * hash) + TARGETACTORNAME_FIELD_NUMBER;
        hash = (53 * hash) + getTargetActorName().hashCode();
      }
      if (hasSourceActorName()) {
        hash = (37 * hash) + SOURCEACTORNAME_FIELD_NUMBER;
        hash = (53 * hash) + getSourceActorName().hashCode();
      }
      if (hasPerformOperation()) {
        hash = (37 * hash) + PERFORMOPERATION_FIELD_NUMBER;
        hash = (53 * hash) + getPerformOperation().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasMsgOption()) {
        hash = (37 * hash) + MSGOPTION_FIELD_NUMBER;
        hash = (53 * hash) + msgOption_;
      }
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sunbird.akka.core.MessageProtos.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        org.sunbird.akka.core.MessageProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sunbird.akka.core.MessageProtos.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sunbird.akka.core.MessageProtos.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sunbird.akka.core.MessageProtos.Message.class, org.sunbird.akka.core.MessageProtos.Message.Builder.class);
      }

      // Construct using org.sunbird.akka.core.MessageProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        targetActorName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceActorName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        performOperation_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msgOption_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        payload_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sunbird.akka.core.MessageProtos.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public org.sunbird.akka.core.MessageProtos.Message getDefaultInstanceForType() {
        return org.sunbird.akka.core.MessageProtos.Message.getDefaultInstance();
      }

      @java.lang.Override
      public org.sunbird.akka.core.MessageProtos.Message build() {
        org.sunbird.akka.core.MessageProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sunbird.akka.core.MessageProtos.Message buildPartial() {
        org.sunbird.akka.core.MessageProtos.Message result = new org.sunbird.akka.core.MessageProtos.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetActorName_ = targetActorName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sourceActorName_ = sourceActorName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.performOperation_ = performOperation_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgOption_ = msgOption_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sunbird.akka.core.MessageProtos.Message) {
          return mergeFrom((org.sunbird.akka.core.MessageProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sunbird.akka.core.MessageProtos.Message other) {
        if (other == org.sunbird.akka.core.MessageProtos.Message.getDefaultInstance()) return this;
        if (other.hasTargetActorName()) {
          bitField0_ |= 0x00000001;
          targetActorName_ = other.targetActorName_;
          onChanged();
        }
        if (other.hasSourceActorName()) {
          bitField0_ |= 0x00000002;
          sourceActorName_ = other.sourceActorName_;
          onChanged();
        }
        if (other.hasPerformOperation()) {
          bitField0_ |= 0x00000004;
          performOperation_ = other.performOperation_;
          onChanged();
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000008;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasMsgOption()) {
          setMsgOption(other.getMsgOption());
        }
        if (other.hasPayload()) {
          bitField0_ |= 0x00000020;
          payload_ = other.payload_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTargetActorName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sunbird.akka.core.MessageProtos.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sunbird.akka.core.MessageProtos.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object targetActorName_ = "";
      /**
       * <code>required string targetActorName = 1;</code>
       */
      public boolean hasTargetActorName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string targetActorName = 1;</code>
       */
      public java.lang.String getTargetActorName() {
        java.lang.Object ref = targetActorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            targetActorName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string targetActorName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTargetActorNameBytes() {
        java.lang.Object ref = targetActorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetActorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string targetActorName = 1;</code>
       */
      public Builder setTargetActorName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        targetActorName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string targetActorName = 1;</code>
       */
      public Builder clearTargetActorName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetActorName_ = getDefaultInstance().getTargetActorName();
        onChanged();
        return this;
      }
      /**
       * <code>required string targetActorName = 1;</code>
       */
      public Builder setTargetActorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        targetActorName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sourceActorName_ = "";
      /**
       * <code>optional string sourceActorName = 2;</code>
       */
      public boolean hasSourceActorName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string sourceActorName = 2;</code>
       */
      public java.lang.String getSourceActorName() {
        java.lang.Object ref = sourceActorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceActorName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sourceActorName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSourceActorNameBytes() {
        java.lang.Object ref = sourceActorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceActorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sourceActorName = 2;</code>
       */
      public Builder setSourceActorName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sourceActorName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sourceActorName = 2;</code>
       */
      public Builder clearSourceActorName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceActorName_ = getDefaultInstance().getSourceActorName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sourceActorName = 2;</code>
       */
      public Builder setSourceActorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sourceActorName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object performOperation_ = "";
      /**
       * <code>optional string performOperation = 3;</code>
       */
      public boolean hasPerformOperation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string performOperation = 3;</code>
       */
      public java.lang.String getPerformOperation() {
        java.lang.Object ref = performOperation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            performOperation_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string performOperation = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPerformOperationBytes() {
        java.lang.Object ref = performOperation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          performOperation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string performOperation = 3;</code>
       */
      public Builder setPerformOperation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        performOperation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string performOperation = 3;</code>
       */
      public Builder clearPerformOperation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        performOperation_ = getDefaultInstance().getPerformOperation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string performOperation = 3;</code>
       */
      public Builder setPerformOperationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        performOperation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 4;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string id = 4;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 4;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 4;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 4;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        id_ = value;
        onChanged();
        return this;
      }

      private int msgOption_ = 0;
      /**
       * <code>optional .MessageOption msgOption = 5;</code>
       */
      public boolean hasMsgOption() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .MessageOption msgOption = 5;</code>
       */
      public org.sunbird.akka.core.MessageProtos.MessageOption getMsgOption() {
        @SuppressWarnings("deprecation")
        org.sunbird.akka.core.MessageProtos.MessageOption result = org.sunbird.akka.core.MessageProtos.MessageOption.valueOf(msgOption_);
        return result == null ? org.sunbird.akka.core.MessageProtos.MessageOption.SEND_AND_FORGET : result;
      }
      /**
       * <code>optional .MessageOption msgOption = 5;</code>
       */
      public Builder setMsgOption(org.sunbird.akka.core.MessageProtos.MessageOption value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        msgOption_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .MessageOption msgOption = 5;</code>
       */
      public Builder clearMsgOption() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgOption_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object payload_ = "";
      /**
       * <code>optional string payload = 6;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string payload = 6;</code>
       */
      public java.lang.String getPayload() {
        java.lang.Object ref = payload_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            payload_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string payload = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPayloadBytes() {
        java.lang.Object ref = payload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string payload = 6;</code>
       */
      public Builder setPayload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string payload = 6;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000020);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      /**
       * <code>optional string payload = 6;</code>
       */
      public Builder setPayloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        payload_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final org.sunbird.akka.core.MessageProtos.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sunbird.akka.core.MessageProtos.Message();
    }

    public static org.sunbird.akka.core.MessageProtos.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sunbird.akka.core.MessageProtos.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\"\225\001\n\007Message\022\027\n\017targetAct" +
      "orName\030\001 \002(\t\022\027\n\017sourceActorName\030\002 \001(\t\022\030\n" +
      "\020performOperation\030\003 \001(\t\022\n\n\002id\030\004 \001(\t\022!\n\tm" +
      "sgOption\030\005 \001(\0162\016.MessageOption\022\017\n\007payloa" +
      "d\030\006 \001(\t*;\n\rMessageOption\022\023\n\017SEND_AND_FOR" +
      "GET\020\000\022\025\n\021GET_BACK_RESPONSE\020\001B&\n\025org.sunb" +
      "ird.akka.coreB\rMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "TargetActorName", "SourceActorName", "PerformOperation", "Id", "MsgOption", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
